import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import "../styles/styles.scss";
const inter = Inter({ subsets: ["latin"] });
import { Button } from "../components/Button/Button";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="theme">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
