import type { Metadata } from 'next'
import './globals.css'
import React from 'react'
import '../styles/styles.scss'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className="theme">
      <body>{children}</body>
    </html>
  )
}
